apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-basic
  labels:
    app: api-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-basic
  template:
    metadata:
      labels:
        app: api-basic
    spec:
      containers:
      - name: api-basic
        image: habolanos/api-basic:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: log-volume
          mountPath: /var/log
      volumes:
      - name: log-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-basic-service
spec:
  selector:
    app: api-basic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer