apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-basic
  labels:
    app: api-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-basic
  template:
    metadata:
      labels:
        app: api-basic
    spec:
      containers:
      - name: api-basic
        image: habolanos/api-basic:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: log-volume
          mountPath: /var/log
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
          requests:
            cpu: "0.1"
            memory: "64Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: log-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-basic-service
spec:
  selector:
    app: api-basic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer